/* mutation常量 */
export const SET_LOADING = 'SET_LOADING'

export const SET_KEEPALIVEPAGES = 'SET_KEEPALIVEPAGES'
export const DELETE_KEEPALIVEPAGES = 'DELETE_KEEPALIVEPAGES'

export const SET_TITLE_BAR = 'SET_TITLE_BAR'
export const UPDATE_TITLE_BAR_TITLE = 'UPDATE_TITLE_BAR_TITLE'

export const SET_CUR_CITY = 'SET_CUR_CITY'
export const SET_LOCAL_CITY = 'SET_LOCAL_CITY'
export const SET_LOCAL_POINT = 'SET_LOCAL_POINT'
export const SET_CITY_LIST = 'SET_CITY_LIST'

export const PARTNER_CITY_SELECT = "PARTNER_CITY_SELECT"
export const SET_AGENT_INFO = "SET_AGENT_INFO"
